---
- name: "stop service"
  community.docker.docker_container:
    name: "{{ cadvisor_image_name }}"
    state: absent
  when: cadvisor_force_update == "yes"

- name: "start service"
  community.docker.docker_container:
    name: "{{ cadvisor_image_name }}"
    image: "{{ cadvisor_image }}:{{ cadvisor_version }}"
    state: started
    detach: true
    tty: false
    restart_policy: always
    container_default_behavior: no_defaults
    privileged: true
    labels: "{{ cadvisor_container_labels | default(omit) }}"
    ports: "{{ cadvisor_published_ports }}"
    volumes:
      - "/:/rootfs:ro"
      - "/etc/machine-id:/etc/machine-id:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
    devices:
      - "/dev/kmsg:/dev/kmsg"

- name: "check service available"
  ansible.builtin.raw: |
    for i in 1 2 3 4 5 6 7 8 9 10
    do
      curl "{{ cadvisor_host_ip }}:{{ cadvisor_host_port }}/metrics" | grep cadvisor_version_info && exit
      sleep 1
    done
    exit 1
  changed_when: false
